Apperance:
  Leftout Width: 600
  Taskbar Height: 40
Lyrics:
  Folder: lyrics
  Global Offset: 0
  Providers:
  - NetEase
  - Lrclib
  - Musixmatch
  SP_DC: ''
  Timing Offset: 0
Playing Info:
  Host: http://localhost
  Port: 7890
  Provider: System
  Spicetify Port: 8974
  Tracking App:
  - Spotify.exe
  - F0DC299D809B9700
  - TheBrowserCompany.Arc_ttt1ap7aakyb4!Arc
  - com.github.th-ch.youtube-music
  - Spotube
  - msedgewebview2.exe
  - com.lyra.music
STT:
  Model Path: ''
  Tracking Input: ''
Themes:
  Default: Soft
  Folder: themes
Display:
  Progress Bar: false
